/* collision_tiles.c */
/* If you are using lit to compile, do not edit this file (collision_tiles.c) directly as it will be overwritten in the main.lit compile process */
/* include_directives */
#include <stdio.h>
#include "tilemap.h"
#include <stdbool.h>

/* @{define_directives} */
/* @{type_definitions} */
/* @{external_variables} */
/* @{function_prototypes} */
int
main(void)
{
	/* @{debug_variables} */
	int travelled_tiles[22][40] = {0};
	printf("Rectangle rects[] = \n{\n");
	/* main_loop */
	for (int y = 0; y < 22; y++) {
		for (int x = 0; x < 40; x++) {
			/* skip_seen_tiles */
			if (travelled_tiles[y][x] != 0) {
				x += travelled_tiles[y][x] - 1; // as the for loop increments as well, we add minus 1 here
				continue;
			}

			int travel_x = 1;
			int travel_y = 1;
			if (tilemap_tileset_0[y][x] == 1) {
				/* go_right_as_far_as_possible */
				bool is_in_bounds;
				bool is_tile_solid;
				bool is_travelled_before;
				for (;;) {
					is_in_bounds = x + travel_x < 40;
					is_tile_solid = tilemap_tileset_0[y][x + travel_x] == 1;
					is_travelled_before = travelled_tiles[y][x + travel_x] != 0;
				
					if (is_in_bounds && is_tile_solid && !(is_travelled_before)) {
						travel_x++;
					}
					else {
						break;
					}
				
				}
				travelled_tiles[y][x] = travel_x; //que to jump ahead travel_x

				/* printf("travel_x = %d, x = %d, y = %d\n", travel_x, x, y ); */
				/* see_how_tall_the_widest_rectangle_is */
				while (tilemap_tileset_0[y + travel_y][x] == 1 && y + travel_y < 22) {
					for (int tx = 0; tx < travel_x; tx++) { // check line is solid
						bool is_hole = tilemap_tileset_0[y + travel_y][x + tx] != 1;
						bool is_travelled_before = travelled_tiles[y + travel_y][x + tx] != 0;
						if ( is_hole || is_travelled_before ) {
							goto end_loop;
						}
					}
					travelled_tiles[y + travel_y][x] = travel_x; //que to jump ahead travel_x
					travel_y++;
				}

				end_loop:
				printf("(Rectangle) {%d,%d,%d,%d},\n", x*32, y*32, travel_x*32, travel_y*32);
				x+= travel_x - 1;
			}
		}
	}

	/* @{debug_print} */

	printf("(Rectangle) {0}// redundant can delete\n};\n");
	return 0;
}

/* @{function_definitions} */

