/* main.c */
/* If you are using lit to compile, do not edit this file (platformer.c) directly as it will be overwritten in the main.lit compile process */
/* include_directives */
#include "raylib.h" // itself includes stdbool.h and stdarg.h
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#if defined(__EMSCRIPTEN__)
	#include <emscripten/emscripten.h>
#endif
#include "tilemap.h"

/* define_directives */
#define TILESIZE 16
#define TILESCALE 2

/* type_definitions */
enum dual_tile_type {
	OUTER_CORNER_0,
	OUTER_CORNER_1,
	OUTER_CORNER_2,
	OUTER_CORNER_3,
	EDGE_CONNECTOR_0,
	EDGE_CONNECTOR_1,
	INNER_CORNER_0,
	INNER_CORNER_1,
	INNER_CORNER_2,
	INNER_CORNER_3,
	BORDER_0,
	BORDER_1,
	BORDER_2,
	BORDER_3,
	OVERLAY_FILL_0,
	UNDERLAY_FILL_0,
};

/* external_variables */
/* const int screen_width = 800; */
/* const int screen_height = 450; */
const int screen_width = 1280;
const int screen_height = 1024;
int tileset_0_dual[22][40];
Texture2D layer_0[UNDERLAY_FILL_0]; // UNDERLAY_FILL_0 is the last enum

/* function_prototypes */
void update_draw_frame(void);
bool is_tile(int x_0, int x_1, int x_2, int x_3, int y_0, int y_1, int y_2, int y_3);
void draw_layer_0(int tileset_0_dual[22][40]);

int
main(void)
{
	SetConfigFlags(FLAG_VSYNC_HINT | FLAG_MSAA_4X_HINT | FLAG_WINDOW_HIGHDPI);
	InitWindow(screen_width, screen_height, "game");
	/* initialise_objects */
	int pos_0, pos_1, pos_2, pos_3;
	for (int x = 0; x < 40 - 1; x++) {
		for (int y = 0; y < 22 - 1; y++) {
			/* outer corner */
			pos_0 = tileset_n[y][x];
			pos_1 = tileset_n[y][x+1];
			pos_2 = tileset_n[y+1][x];
			pos_3 = tileset_n[y+1][x+1];
	
			/* outer corner */
			if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,0 ,0 ,0)){
				tileset_0_dual[y][x] = OUTER_CORNER_0;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,1 ,0 ,0)) {
				tileset_0_dual[y][x] = OUTER_CORNER_1;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,0 ,0 ,1)) {
				tileset_0_dual[y][x] = OUTER_CORNER_2;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,0 ,1 ,0)) {
				tileset_0_dual[y][x] = OUTER_CORNER_3;
			}
	
			/* edge connectors */
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,0 ,0 ,1)) {
				tileset_0_dual[y][x] = EDGE_CONNECTOR_0;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,1 ,1 ,0)) {
				tileset_0_dual[y][x] = EDGE_CONNECTOR_1;
			}
	
			/* inner corner */
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,1 ,1 ,1)) {
				tileset_0_dual[y][x] = INNER_CORNER_0;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,0 ,1 ,1)) {
				tileset_0_dual[y][x] = INNER_CORNER_1;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,1 ,1 ,0)) {
				tileset_0_dual[y][x] = INNER_CORNER_2;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,1 ,0 ,1)) {
				tileset_0_dual[y][x] = INNER_CORNER_3;
			}
	
			/* border */
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,1 ,0 ,0)) {
				tileset_0_dual[y][x] = BORDER_0;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,1 ,0 ,1)) {
				tileset_0_dual[y][x] = BORDER_1;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,0 ,1 ,1)) {
				tileset_0_dual[y][x] = BORDER_2;
			}
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,0 ,1 ,0)) {
				tileset_0_dual[y][x] = BORDER_3;
			}
	
			/* overlay fill */
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 1 ,1 ,1 ,1)) {
				tileset_0_dual[y][x] = OVERLAY_FILL_0;
			}
	
			/* underlay fill */
			else if (is_tile(pos_0, pos_1, pos_2, pos_3, 0 ,0 ,0 ,0)) {
				tileset_0_dual[y][x] = UNDERLAY_FILL_0;
			}
	
		}
	}
	layer_0[OUTER_CORNER_0] = LoadTexture("assets/tileset1/outer_corner_0.gif");
	layer_0[OUTER_CORNER_1] = LoadTexture("assets/tileset1/outer_corner_1.gif");
	layer_0[OUTER_CORNER_2] = LoadTexture("assets/tileset1/outer_corner_2.gif");
	layer_0[OUTER_CORNER_3] = LoadTexture("assets/tileset1/outer_corner_3.gif");
	layer_0[EDGE_CONNECTOR_0] = LoadTexture("assets/tileset1/edge_connector_0.gif");
	layer_0[EDGE_CONNECTOR_1] = LoadTexture("assets/tileset1/edge_connector_1.gif");
	layer_0[INNER_CORNER_0] = LoadTexture("assets/tileset1/inner_corner_0.gif");
	layer_0[INNER_CORNER_1] = LoadTexture("assets/tileset1/inner_corner_1.gif");
	layer_0[INNER_CORNER_2] = LoadTexture("assets/tileset1/inner_corner_2.gif");
	layer_0[INNER_CORNER_3] = LoadTexture("assets/tileset1/inner_corner_3.gif");
	layer_0[BORDER_0] = LoadTexture("assets/tileset1/border_0.gif");
	layer_0[BORDER_1] = LoadTexture("assets/tileset1/border_1.gif");
	layer_0[BORDER_2] = LoadTexture("assets/tileset1/border_2.gif");
	layer_0[BORDER_3] = LoadTexture("assets/tileset1/border_3.gif");
	layer_0[OVERLAY_FILL_0] = LoadTexture("assets/tileset1/overlay_fill_0.gif");
	layer_0[UNDERLAY_FILL_0] = LoadTexture("assets/tileset1/underlay_fill_0.gif");

#if defined(__EMSCRIPTEN__)
	emscripten_set_main_loop(update_draw_frame, 0, 1);
#else
	SetTargetFPS(60);
	while (!WindowShouldClose())
	{
		update_draw_frame();
	}
#endif
	/* de_init */
	for (int i = 0; i < UNDERLAY_FILL_0; i++) {
		UnloadTexture(layer_0[i]);
	}

	CloseWindow();
	return 0;
}

/* function_definitions */
void
update_draw_frame(void)
{
	/* update */
	

	
	/* opengl draw context */
	BeginDrawing();
	ClearBackground(RAYWHITE);
	/* draw */
	draw_layer_0(tileset_0_dual);

	EndDrawing();
}
bool
is_tile(int x_0, int x_1, int x_2, int x_3, int y_0, int y_1, int y_2, int y_3)
{
	if (x_0 == y_0 && x_1 == y_1 && x_2 == y_2 && x_3 == y_3) {
		return true;
	}
	return false;
}
void
draw_layer_0(int tileset_0_dual[22][40])
{
	for (int x = 0; x < 40 - 1; x++) {
		for (int y = 0; y < 22 - 1; y++) {
			Vector2 draw_pos = {x*(TILESIZE*TILESCALE), y*(TILESIZE*TILESCALE)};
			int tile = tileset_0_dual[y][x];
			DrawTextureEx(layer_0[tile], draw_pos, 0, TILESCALE, WHITE);
		}
	}
}



